services:
  frontend:
    container_name: wish-magic-frontend-dev
    image: wish-magic-frontend:dev
    depends_on:
      - backend
    restart: on-failure
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3001:3000

  backend:
    container_name: wish-magic-backend-dev
    depends_on:
      - db
    image: wish-magic-backend:dev
    restart: on-failure
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/src:/app/src
    ports:
      - 4000:3000
    env_file:
      - ./backend/.env.development

  db:
    container_name: wish-magic-postgres-dev
    image: postgres:14.3-alpine
    restart: on-failure
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env.development

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
