FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json .

COPY ./docs/openapi.yaml ./docs/openapi.yaml

RUN npm ci --no-audit --no-fund

COPY . .

RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app

COPY package*.json .

COPY ./docs/openapi.yaml ./docs/openapi.yaml

RUN npm ci --omit=dev --no-audit --no-fund && \
    npm i -g pm2

COPY --from=builder /app/build ./build

COPY ecosystem.config.js .

CMD ["pm2-runtime", "start", "ecosystem.config.js"]

