FROM node:20-alpine

WORKDIR /app

COPY package*.json docs/ ./

# install exactly the same package version as in current project
RUN npm ci --no-audit --no-fund

COPY . .

EXPOSE 3000

CMD npm run start:dev