FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json docs/ ./

RUN npm ci --no-audit --no-fund

COPY . .

EXPOSE 3000

RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app

COPY package*.json docs/ ./

RUN npm ci --omit=dev --no-audit --no-fund && \
    npm i -g pm2

COPY --from=builder /app/build ./build

COPY ecosystem.config.js .

CMD ["pm2-runtime", "start", "ecosystem.config.js"]

