### Create offer
POST http://localhost:3000/api/v1/offers/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZWMzZGE0NS03OWRlLTQxZDktOGI0OS1mOGY2Y2NmNDlkNDgiLCJpYXQiOjE3MTMzNDU2NTEsImV4cCI6MTcxMzQzMjA1MX0.1OUtpIp-hYptu12H4buZ0wO15vhbBw-Gssx2IakqaI0

{
  "wishId": "34415323-cff8-4f99-871e-a5073c55da3e",
  "amount": 10
}

### Get All Offers
Get http://localhost:3000/api/v1/offers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZWMzZGE0NS03OWRlLTQxZDktOGI0OS1mOGY2Y2NmNDlkNDgiLCJpYXQiOjE3MTMzNDU2NTEsImV4cCI6MTcxMzQzMjA1MX0.1OUtpIp-hYptu12H4buZ0wO15vhbBw-Gssx2IakqaI0

### Get Offer by id
Get http://localhost:3000/api/v1/offers/d24110c2-8bbd-4ad4-b877-3b212daa6709
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZWMzZGE0NS03OWRlLTQxZDktOGI0OS1mOGY2Y2NmNDlkNDgiLCJpYXQiOjE3MTMzNDU2NTEsImV4cCI6MTcxMzQzMjA1MX0.1OUtpIp-hYptu12H4buZ0wO15vhbBw-Gssx2IakqaI0

### Get Wish by id
GET http://localhost:3000/api/v1/wishes/7bc5829a-86d4-4fb2-b9f8-8f95199ae734
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZWMzZGE0NS03OWRlLTQxZDktOGI0OS1mOGY2Y2NmNDlkNDgiLCJpYXQiOjE3MTMzNDU2NTEsImV4cCI6MTcxMzQzMjA1MX0.1OUtpIp-hYptu12H4buZ0wO15vhbBw-Gssx2IakqaI0

### Get Me wishes
GET http://localhost:3000/api/v1/users/me/wishes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwZWMzZGE0NS03OWRlLTQxZDktOGI0OS1mOGY2Y2NmNDlkNDgiLCJpYXQiOjE3MTMzNDU2NTEsImV4cCI6MTcxMzQzMjA1MX0.1OUtpIp-hYptu12H4buZ0wO15vhbBw-Gssx2IakqaI0